namespace Valaiorp.Configuration.Loader
{
    using System.Text;
    using System.Text.Json;
    using System.Text.Json.Serialization;
    using Valaiorp.Configuration.Config;

    /// <summary>
    /// Loads <c>valaiorp.json</c> from disk, or writes a fully-annotated template
    /// if no file is found, so users can discover all options without reading source code.
    ///
    /// Usage:
    ///   var config = ValaiorpConfigurationLoader.LoadOrCreate();          // auto-finds / auto-creates
    ///   var config = ValaiorpConfigurationLoader.Load("path/to/file.json"); // explicit path
    ///   ValaiorpConfigurationLoader.WriteTemplate("valaiorp.json");        // generate template only
    /// </summary>
    public static class ValaiorpConfigurationLoader
    {
        public const string DefaultFileName = "valaiorp.json";

        private static readonly JsonSerializerOptions ReadOptions = new()
        {
            PropertyNameCaseInsensitive = true,
            ReadCommentHandling = JsonCommentHandling.Skip,
            AllowTrailingCommas = true,
            Converters = { new JsonStringEnumConverter() }
        };

        private static readonly JsonSerializerOptions WriteOptions = new()
        {
            WriteIndented = true,
            Converters = { new JsonStringEnumConverter() }
        };

        /// <summary>
        /// Searches for <c>valaiorp.json</c> in the current directory, then the application
        /// base directory. If not found, writes a template to the current directory and
        /// returns framework defaults so the application can still start.
        /// </summary>
        public static ValaiorpConfig LoadOrCreate(string? filePath = null)
        {
            var resolved = filePath ?? FindConfigFile();

            if (resolved is null)
            {
                resolved = Path.Combine(Directory.GetCurrentDirectory(), DefaultFileName);
                WriteTemplate(resolved);
                // Return defaults — the generated file documents every option.
                return new ValaiorpConfig();
            }

            return Load(resolved);
        }

        /// <summary>Loads and deserialises an existing config file (JSONC comments supported).</summary>
        public static ValaiorpConfig Load(string filePath)
        {
            var json = File.ReadAllText(filePath, Encoding.UTF8);
            var config = JsonSerializer.Deserialize<ValaiorpConfig>(json, ReadOptions)
                         ?? new ValaiorpConfig();
            Normalize(config);
            return config;
        }

        // Post-load normalization for sentinel values that can't be expressed in JSON.
        private static void Normalize(ValaiorpConfig config)
        {
            if (config.Parallelism.MaxDegreeOfParallelism <= 0)
                config.Parallelism.MaxDegreeOfParallelism = Environment.ProcessorCount;
        }

        /// <summary>
        /// Writes a fully-annotated JSONC template with every option and its allowed values
        /// to <paramref name="filePath"/>. Overwrites existing file.
        /// </summary>
        public static void WriteTemplate(string filePath)
        {
            var dir = Path.GetDirectoryName(filePath);
            if (!string.IsNullOrEmpty(dir))
                Directory.CreateDirectory(dir);

            File.WriteAllText(filePath, TemplateContent, Encoding.UTF8);
        }

        /// <summary>
        /// Searches known locations for <c>valaiorp.json</c>.
        /// Returns the first path that exists, or null.
        /// </summary>
        public static string? FindConfigFile(string fileName = DefaultFileName)
        {
            string[] candidates =
            [
                Path.Combine(Directory.GetCurrentDirectory(), fileName),
                Path.Combine(AppContext.BaseDirectory, fileName),
            ];
            return candidates.FirstOrDefault(File.Exists);
        }

        // ─── Annotated JSONC template ─────────────────────────────────────────────
        // Embedded as a constant so it stays in sync with the models at compile time.
        // Comments use // style; the loader reads with JsonCommentHandling.Skip.

        internal const string TemplateContent = """
            // valaiorp.json — Valaiorp framework configuration
            // Auto-generated by ValaiorpConfigurationLoader. Edit then restart.
            // All fields are optional; the values shown are the defaults.
            // Tip: the loader accepts // and /* */ comments so you can annotate freely.
            {
              // ─── LLM ──────────────────────────────────────────────────────────────────
              // Remove this section entirely if you are not using AI / LLM planning.
              "Llm": {

                // REQUIRED when using AI. Identifies the LLM provider.
                // Allowed: "anthropic" | "openai" | "ollama" | "custom"
                "Provider": "anthropic",

                // REQUIRED. Model identifier exactly as the provider names it.
                //   Anthropic examples : "claude-sonnet-4-6" | "claude-opus-4-7" | "claude-haiku-4-5-20251001"
                //   OpenAI examples    : "gpt-4o" | "gpt-4o-mini" | "o1-preview"
                //   Ollama examples    : "llama3" | "mistral" | "phi3"  (any locally pulled model)
                "ModelId": "claude-sonnet-4-6",

                // ── API key resolution ─────────────────────────────────────────────────
                // Use exactly ONE of the three options below. Resolution order:
                //   1. ApiKey      — literal string in this file (dev / local only, NOT for production)
                //   2. ApiKeyEnvVar— name of an environment variable that holds the key
                //   3. ApiKeyFile  — path to a file whose first non-empty line is the key
                //                   (ideal for Docker secrets mounts, CI artefacts)
                //
                // For secrets vaults (Azure Key Vault, AWS Secrets Manager, HashiCorp Vault, etc.)
                // implement IApiKeyProvider and pass it to AddLlmClient(config, myProvider).
                "ApiKey": "",
                "ApiKeyEnvVar": "ANTHROPIC_API_KEY",
                "ApiKeyFile": "",

                // Optional. Overrides the provider's default base URL.
                //   Useful for: Ollama local endpoint, Azure OpenAI, corporate proxy.
                //   Leave empty to use the provider's public default.
                "BaseUrl": "",

                // Optional. Default system prompt injected at the start of every plan request.
                // Supports {variable} substitution via PromptContext.Variables.
                "SystemPromptTemplate": "",

                // Maximum tokens the LLM may generate in a single response.
                "MaxTokens": 4096,

                // Sampling temperature: 0.0 = deterministic / factual,  1.0 = creative / random.
                "Temperature": 0.7,

                // HTTP timeout for a single LLM round-trip (format: "hh:mm:ss").
                "RequestTimeout": "00:02:00"
              },

              // ─── PLANNER ──────────────────────────────────────────────────────────────
              "Planner": {

                // Controls how plans are built from a user request.
                // Allowed: "Reactive" | "Deliberative" | "Hierarchical" | "None"
                //   Reactive     — single-pass, fast (default; no LLM required)
                //   Deliberative — 3-pass LLM loop: draft → self-critique → revise
                //                  Requires the Llm section above to be configured.
                //   Hierarchical — top-level plan decomposes into nested sub-plans
                //   None         — skip planning; execute a single raw step
                "Type": "Reactive",

                // Maximum recursive depth when decomposing a hierarchical plan.
                "MaxDepth": 10,

                // Maximum number of parallel branches at each plan node.
                "MaxBranchingFactor": 5,

                // Allow the planner to backtrack and retry an alternative branch on failure.
                "EnableBacktracking": true,

                // Wall-clock timeout for the entire planning phase (format: "hh:mm:ss").
                "PlanningTimeout": "00:00:30"
              },

              // ─── EXECUTION ────────────────────────────────────────────────────────────
              "Execution": {

                // Controls step execution order.
                // Allowed: "Sequential" | "Parallel" | "Hybrid"
                "Mode": "Sequential",

                // Overall wall-clock timeout for a single ExecutionUnit (format: "hh:mm:ss").
                "Timeout": "00:05:00",

                // Number of automatic retries before a step is marked as failed.
                "MaxRetries": 3,

                // Circuit breaker prevents cascading failures by stopping calls to a
                // consistently failing tool until it recovers.
                "EnableCircuitBreaker": true,

                // Open (trip) the circuit after this many consecutive failures.
                "CircuitBreakerThreshold": 5,

                // How long to hold the circuit open before attempting a test call (format: "hh:mm:ss").
                "CircuitBreakerResetTime": "00:00:30"
              },

              // ─── PARALLELISM ──────────────────────────────────────────────────────────
              "Parallelism": {

                // Maximum concurrent tasks. 0 = auto-detect (uses Environment.ProcessorCount).
                "MaxDegreeOfParallelism": 0,

                // Hard cap on simultaneous ExecutionUnit instances across the runtime.
                "MaxConcurrentExecutions": 10,

                // Allow the runtime to grow/shrink the thread pool based on load.
                "EnableDynamicScaling": true,

                "MinThreadPoolSize": 4,
                "MaxThreadPoolSize": 50
              },

              // ─── KNOWLEDGE (RAG) ──────────────────────────────────────────────────────
              // Controls retrieval-augmented generation. Remove this section to disable RAG.
              "Knowledge": {

                // Provider used to generate embeddings for semantic search.
                // Allowed: "openai" | "ollama" | "custom" — leave empty to disable RAG.
                "EmbeddingProvider": "",

                // Embedding model ID as the provider names it.
                //   OpenAI examples : "text-embedding-3-small" | "text-embedding-3-large"
                //   Ollama examples : "nomic-embed-text" | "mxbai-embed-large"
                "EmbeddingModel": "",

                // Vector dimension must match the model above.
                //   text-embedding-3-small = 1536,  text-embedding-3-large = 3072
                "EmbeddingDimension": 1536,

                // Minimum cosine similarity [0.0–1.0] for a chunk to be included in context.
                // Higher = stricter / fewer results.
                "SimilarityThreshold": 0.75,

                // Token budget for injected RAG content per prompt.
                "MaxContextLength": 4096,

                // Maximum number of knowledge chunks injected into each prompt.
                "MaxKnowledgeResults": 5
              },

              // ─── GOVERNANCE ───────────────────────────────────────────────────────────
              "Governance": {

                // Emit a structured audit record for every step execution.
                "EnableAuditLogging": true,

                // Collect execution metrics (latency, token usage, tool call counts).
                "EnableMetrics": true,

                // Apply per-second rate limiting across all tool and LLM calls.
                "EnableRateLimiting": true,
                "MaxRequestsPerSecond": 100,

                // Reject any step whose input or output contains a banned keyword.
                "EnableContentModeration": true,

                // List of words/phrases that trigger content moderation rejection.
                "BannedKeywords": []
              },

              // ─── AUTONOMY ─────────────────────────────────────────────────────────────
              "Autonomy": {

                // Continuous autonomy level from 0.0 (fully deterministic) to 1.0 (fully agentic).
                // The corresponding named mode is derived automatically:
                //   0.0 – 0.1  →  FullyDeterministic : strict rules, no agentic behaviour
                //   0.1 – 0.4  →  ControlledHybrid   : limited agentic decisions with approval gates
                //   0.4 – 0.7  →  AssistedAgentic    : mostly agentic with guardrails
                //   0.7 – 1.0  →  FullyAgentic       : full agentic freedom (use with caution)
                //
                // Alternatively, set "Mode" to one of the names above and Level is set automatically.
                "Level": 0.0,

                // Allow the agent to extend or modify its own plan mid-execution.
                "AllowDynamicPlanning": false,

                // Allow the agent to choose which tools to invoke (vs. fixed plan).
                "AllowToolSelection": false,

                // Allow if/else branching within a plan based on runtime results.
                "AllowConditionalBranching": true,

                // Pause and request human approval before executing high-risk steps.
                "RequireApprovalForHighRisk": true
              }
            }
            """;
    }
}
